import Foundation
import CoreGraphics

public enum MIRAUsernameRules {
  public static func normalized(_ value: String?) -> String {
    (value ?? "")
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .lowercased()
      .replacingOccurrences(of: "^@+", with: "", options: .regularExpression)
  }

  public static func isValidPublicUsername(_ value: String?) -> Bool {
    let username = normalized(value)
    guard (3...20).contains(username.count) else { return false }
    guard username.range(of: #"^[a-z0-9_.]+$"#, options: .regularExpression) != nil else { return false }
    guard !username.hasPrefix("."), !username.hasSuffix("."), !username.contains("..") else { return false }
    return !reservedUsernames.contains(username) && !looksAutoGenerated(username)
  }

  public static func looksAutoGenerated(_ value: String?) -> Bool {
    let username = normalized(value)
    guard !username.isEmpty else { return true }
    if generatedPrefixes.contains(where: { username.hasPrefix($0) }) { return true }
    if username.range(of: #"^[0-9a-f]{8,32}$"#, options: .regularExpression) != nil { return true }
    if username.range(of: #"^[0-9a-f]{6,12}$"#, options: .regularExpression) != nil,
       username.rangeOfCharacter(from: .decimalDigits) != nil {
      return true
    }
    if username.range(of: #"^[a-z0-9]{6,10}$"#, options: .regularExpression) != nil {
      let letters = username.replacingOccurrences(of: #"[^a-z]"#, with: "", options: .regularExpression)
      let vowels = letters.filter { "aeiou".contains($0) }.count
      if vowels == 0 { return true }
      if letters.range(of: #"[bcdfghjklmnpqrstvwxyz]{5,}"#, options: .regularExpression) != nil { return true }
    }
    return false
  }

  private static let generatedPrefixes = [
    "user_",
    "temp_",
    "apple_",
    "appleuser",
    "google_",
    "guest_",
    "pending_",
    "phone_",
    "sb_",
    "nulluser"
  ]

  private static let reservedUsernames: Set<String> = [
    "admin", "administrator", "support", "help", "official", "captro", "team",
    "privacy", "terms", "safety", "legal", "moderator", "system", "root", "api",
    "login", "signup", "settings", "discover", "explore", "feed", "chat",
    "profile", "notifications"
  ]
}

public struct MIRAUser: Codable, Identifiable, Hashable {
  public let id: String
  public let username: String?
  public let usernameRequired: Bool?
  public let onboardingRequired: Bool?
  public let fullName: String?
  public let profileImage: String?
  public let bio: String?
  public let email: String?
  public let phone: String?
  public let phoneVerified: Bool?
  public let followersCount: Int?
  public let followingCount: Int?
  public let postsCount: Int?
  public let isFollowing: Bool?
  public let isPrivate: Bool?
  public let isPremium: Bool?
  public let language: String?

  public var displayName: String {
    if MIRAUsernameRules.isValidPublicUsername(username) {
      return MIRAUsernameRules.normalized(username)
    }
    if let fullName, !fullName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      return fullName.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    return "Captro"
  }

  public var needsUsernameOnboarding: Bool {
    usernameRequired == true || onboardingRequired == true || !MIRAUsernameRules.isValidPublicUsername(username)
  }

  public var viewerFollowing: Bool {
    isFollowing == true
  }
}

public struct MIRAPost: Codable, Identifiable, Hashable {
  public let id: String
  public let userId: String?
  public let userUsername: String?
  public let userFullName: String?
  public let userProfileImage: String?
  public let title: String?
  public let content: String?
  public let caption: String?
  public let image: String?
  public let images: FlexibleStringArray?
  public let feedMediaUrls: FlexibleStringArray?
  public let thumbnailUrls: FlexibleStringArray?
  public let posterUrls: FlexibleStringArray?
  public let mediaTypes: FlexibleStringArray?
  public let mediaDimensions: FlexibleMediaDimensions?
  public let location: String?
  public let postType: String?
  public let visibility: String?
  public let placeId: String?
  public let placeName: String?
  public let placeLat: Double?
  public let placeLng: Double?
  public let taggedUsers: [MIRATaggedUserPayload]?
  public let createdAt: String?
  public let likesCount: Int?
  public let commentsCount: Int?
  public let savesCount: Int?
  public let sharesCount: Int?
  public let viewsCount: Int?
  public let pinnedAt: String?
  public let isLiked: Bool?
  public let isSaved: Bool?
  public let isFollowing: Bool?
  public let saved: FlexibleBool?
  public let following: FlexibleBool?
  public let followed: FlexibleBool?

  public var titleText: String {
    if let title, !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      return title.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    let raw = (caption?.isEmpty == false ? caption : content) ?? ""
    let first = raw.components(separatedBy: .newlines).first ?? raw
    return first.isEmpty ? "MIRA post" : first
  }

  public var bodyText: String {
    if let title, !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      return ((caption?.isEmpty == false ? caption : content) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    }
    let raw = (caption?.isEmpty == false ? caption : content) ?? ""
    let lines = raw.components(separatedBy: .newlines).filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
    return lines.count > 1 ? lines.dropFirst().joined(separator: "\n") : ""
  }

  public var mediaURLs: [String] {
    uniqueMediaURLs(from: images?.values ?? [], fallback: image)
  }

  public var feedMediaURLs: [String] {
    let optimized = uniqueMediaURLs(from: feedMediaUrls?.values ?? [], fallback: nil)
    return optimized.isEmpty ? mediaURLs : optimized
  }

  public var thumbnailMediaURLs: [String] {
    let thumbnails = uniqueMediaURLs(from: thumbnailUrls?.values ?? [], fallback: nil)
    return thumbnails.isEmpty ? feedMediaURLs : thumbnails
  }

  public var posterMediaURLs: [String] {
    let posters = uniqueMediaURLs(from: posterUrls?.values ?? [], fallback: nil)
    return posters.isEmpty ? thumbnailMediaURLs : posters
  }

  private func uniqueMediaURLs(from values: [String], fallback: String?) -> [String] {
    var urls: [String] = []
    if let fallback, !fallback.isEmpty { urls.append(fallback) }
    urls.append(contentsOf: values)
    var seen = Set<String>()
    return urls.filter { seen.insert($0).inserted }
  }

  public var mediaHeightToWidthRatios: [CGFloat] {
    mediaDimensions?.values.compactMap(\.heightToWidthRatio) ?? []
  }

  public var placeDisplayName: String? {
    let name = placeName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    if !name.isEmpty { return name }
    let fallback = location?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    return fallback.isEmpty ? nil : fallback
  }

  public var placeDisplaySubtitle: String? {
    guard
      let location,
      !location.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
      location.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() != (placeDisplayName ?? "").lowercased()
    else {
      return nil
    }
    return location.trimmingCharacters(in: .whitespacesAndNewlines)
  }

  public var authorDisplayName: String {
    if MIRAUsernameRules.isValidPublicUsername(userUsername) {
      return MIRAUsernameRules.normalized(userUsername)
    }
    if let userFullName, !userFullName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      return userFullName.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    return "Captro"
  }

  public var viewerSaved: Bool {
    if let isSaved { return isSaved }
    return saved?.value == true
  }

  public var viewerFollowing: Bool {
    if let isFollowing { return isFollowing }
    return following?.value == true || followed?.value == true
  }

  public var isPinned: Bool {
    !(pinnedAt?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
  }

  public func updating(
    liked: Bool? = nil,
    likesCount: Int? = nil,
    commentsCount: Int? = nil,
    saved: Bool? = nil,
    savesCount: Int? = nil,
    following: Bool? = nil
  ) -> MIRAPost {
    MIRAPost(
      id: id,
      userId: userId,
      userUsername: userUsername,
      userFullName: userFullName,
      userProfileImage: userProfileImage,
      title: title,
      content: content,
      caption: caption,
      image: image,
      images: images,
      feedMediaUrls: feedMediaUrls,
      thumbnailUrls: thumbnailUrls,
      posterUrls: posterUrls,
      mediaTypes: mediaTypes,
      mediaDimensions: mediaDimensions,
      location: location,
      postType: postType,
      visibility: visibility,
      placeId: placeId,
      placeName: placeName,
      placeLat: placeLat,
      placeLng: placeLng,
      taggedUsers: taggedUsers,
      createdAt: createdAt,
      likesCount: likesCount ?? self.likesCount,
      commentsCount: commentsCount ?? self.commentsCount,
      savesCount: savesCount ?? self.savesCount,
      sharesCount: sharesCount,
      viewsCount: viewsCount,
      pinnedAt: pinnedAt,
      isLiked: liked ?? isLiked,
      isSaved: saved ?? isSaved,
      isFollowing: following ?? isFollowing,
      saved: self.saved,
      following: self.following,
      followed: self.followed
    )
  }

  public func updatingPinned(at value: String?) -> MIRAPost {
    MIRAPost(
      id: id,
      userId: userId,
      userUsername: userUsername,
      userFullName: userFullName,
      userProfileImage: userProfileImage,
      title: title,
      content: content,
      caption: caption,
      image: image,
      images: images,
      feedMediaUrls: feedMediaUrls,
      thumbnailUrls: thumbnailUrls,
      posterUrls: posterUrls,
      mediaTypes: mediaTypes,
      mediaDimensions: mediaDimensions,
      location: location,
      postType: postType,
      visibility: visibility,
      placeId: placeId,
      placeName: placeName,
      placeLat: placeLat,
      placeLng: placeLng,
      taggedUsers: taggedUsers,
      createdAt: createdAt,
      likesCount: likesCount,
      commentsCount: commentsCount,
      savesCount: savesCount,
      sharesCount: sharesCount,
      viewsCount: viewsCount,
      pinnedAt: value,
      isLiked: isLiked,
      isSaved: isSaved,
      isFollowing: isFollowing,
      saved: saved,
      following: following,
      followed: followed
    )
  }
}

public struct MIRATaggedUserPayload: Codable, Hashable, Identifiable {
  public let id: String
  public let username: String?
  public let fullName: String?
  public let profileImage: String?

  public init(id: String, username: String?, fullName: String?, profileImage: String?) {
    self.id = id
    self.username = username
    self.fullName = fullName
    self.profileImage = profileImage
  }
}

public struct MIRAMediaDimension: Codable, Hashable {
  public let width: Double?
  public let height: Double?
  public let ratio: Double?
  public let format: String?
  public let type: String?

  enum CodingKeys: String, CodingKey {
    case width
    case height
    case ratio
    case aspectRatio
    case aspectRatioSnake = "aspect_ratio"
    case format
    case type
  }

  public init(width: Double?, height: Double?, ratio: Double?, format: String?, type: String?) {
    self.width = width
    self.height = height
    self.ratio = ratio
    self.format = format
    self.type = type
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    width = Self.decodeDouble(container, keys: [.width])
    height = Self.decodeDouble(container, keys: [.height])
    ratio = Self.decodeDouble(container, keys: [.ratio, .aspectRatio, .aspectRatioSnake])
    let explicitFormat = try? container.decodeIfPresent(String.self, forKey: .format)
    let ratioText = Self.decodeString(container, keys: [.ratio, .aspectRatio, .aspectRatioSnake])
    format = explicitFormat ?? ratioText
    type = try? container.decodeIfPresent(String.self, forKey: .type)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(width, forKey: .width)
    try container.encodeIfPresent(height, forKey: .height)
    try container.encodeIfPresent(ratio, forKey: .ratio)
    try container.encodeIfPresent(format, forKey: .format)
    try container.encodeIfPresent(type, forKey: .type)
  }

  public var heightToWidthRatio: CGFloat? {
    let widthValue = width ?? 0
    let heightValue = height ?? 0
    if widthValue > 0, heightValue > 0 {
      return CGFloat(heightValue / widthValue)
    }
    if let ratio, ratio > 0 {
      // Backend stores ratio as width / height. Feed sizing needs height / width.
      return CGFloat(1 / ratio)
    }
    return MIRAMediaSizing.heightToWidthRatio(forFormat: format)
  }

  private static func decodeDouble(_ container: KeyedDecodingContainer<CodingKeys>, keys: [CodingKeys]) -> Double? {
    for key in keys {
      if let value = try? container.decodeIfPresent(Double.self, forKey: key) {
        return value
      }
      if let intValue = try? container.decodeIfPresent(Int.self, forKey: key) {
        return Double(intValue)
      }
      if let string = try? container.decodeIfPresent(String.self, forKey: key),
         let value = Double(string.trimmingCharacters(in: .whitespacesAndNewlines)) {
        return value
      }
    }
    return nil
  }

  private static func decodeString(_ container: KeyedDecodingContainer<CodingKeys>, keys: [CodingKeys]) -> String? {
    for key in keys {
      if let string = try? container.decodeIfPresent(String.self, forKey: key) {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
      }
    }
    return nil
  }
}

public struct MIRANote: Codable, Identifiable, Hashable {
  public let id: String
  public let body: String?
  public let mediaUrl: String?
  public let createdAt: String?
  public let reactionsCount: Int?
  public let commentsCount: Int?
  public let sharesCount: Int?
  public let reacted: Bool?
  public let user: MIRAUser?

  public func updating(reactionsCount: Int? = nil, commentsCount: Int? = nil, sharesCount: Int? = nil, reacted: Bool? = nil) -> MIRANote {
    MIRANote(
      id: id,
      body: body,
      mediaUrl: mediaUrl,
      createdAt: createdAt,
      reactionsCount: reactionsCount ?? self.reactionsCount,
      commentsCount: commentsCount ?? self.commentsCount,
      sharesCount: sharesCount ?? self.sharesCount,
      reacted: reacted ?? self.reacted,
      user: user
    )
  }
}

public struct MIRAGifItem: Decodable, Identifiable, Hashable {
  public let id: String
  public let title: String?
  public let previewUrl: String?
  public let mediaUrl: String?
  public let width: Int?
  public let height: Int?
}

public struct MIRAGifSearchResponse: Decodable, Hashable {
  public let gifs: [MIRAGifItem]
}

public struct MIRAStatusPreview: Codable, Identifiable, Hashable {
  public let id: String
  public let userId: String?
  public let content: String?
  public let image: String?
  public let backgroundColor: String?
  public let textColor: String?
  public let createdAt: String?
  public let expiresAt: String?

  public var mediaURL: String? {
    guard let image, !image.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
    return image
  }
}

public struct MIRAStoryGroup: Codable, Identifiable, Hashable {
  public var id: String { userId }
  public let userId: String
  public let userUsername: String?
  public let userFullName: String?
  public let userProfileImage: String?
  public let hasUnviewed: Bool?
  public let statuses: [MIRAStatusPreview]?

  public var displayName: String {
    if let userFullName, !userFullName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      return userFullName.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    if MIRAUsernameRules.isValidPublicUsername(userUsername) {
      return MIRAUsernameRules.normalized(userUsername)
    }
    return "Story"
  }
}

public struct MIRAComment: Decodable, Identifiable, Hashable {
  public let id: String
  public let userId: String?
  public let postId: String?
  public let postUserId: String?
  public let content: String?
  public let body: String?
  public let parentId: String?
  public let createdAt: String?
  public let likesCount: Int?
  public let likedByMe: Bool?
  public let pinnedAt: String?
  public let isPinned: Bool?
  public let user: MIRAUser?

  public var text: String { body ?? content ?? "" }

  public var viewerLiked: Bool { likedByMe == true }

  public var pinned: Bool {
    isPinned == true || !(pinnedAt?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
  }

  public var isReply: Bool {
    !(parentId?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
  }

  public init(
    id: String,
    userId: String?,
    postId: String?,
    postUserId: String?,
    content: String?,
    body: String?,
    parentId: String?,
    createdAt: String?,
    likesCount: Int?,
    likedByMe: Bool?,
    pinnedAt: String?,
    isPinned: Bool?,
    user: MIRAUser?
  ) {
    self.id = id
    self.userId = userId
    self.postId = postId
    self.postUserId = postUserId
    self.content = content
    self.body = body
    self.parentId = parentId
    self.createdAt = createdAt
    self.likesCount = likesCount
    self.likedByMe = likedByMe
    self.pinnedAt = pinnedAt
    self.isPinned = isPinned
    self.user = user
  }

  enum CodingKeys: String, CodingKey {
    case id
    case userId
    case postId
    case postUserId
    case content
    case body
    case parentId
    case createdAt
    case likesCount
    case likedByMe
    case pinnedAt
    case isPinned
    case user
    case userUsername
    case userFullName
    case userProfileImage
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    id = try container.decode(String.self, forKey: .id)
    userId = try container.decodeIfPresent(String.self, forKey: .userId)
    postId = try container.decodeIfPresent(String.self, forKey: .postId)
    postUserId = try container.decodeIfPresent(String.self, forKey: .postUserId)
    content = try container.decodeIfPresent(String.self, forKey: .content)
    body = try container.decodeIfPresent(String.self, forKey: .body)
    parentId = try container.decodeIfPresent(String.self, forKey: .parentId)
    createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt)
    likesCount = try container.decodeIfPresent(Int.self, forKey: .likesCount)
    likedByMe = try container.decodeIfPresent(Bool.self, forKey: .likedByMe)
    pinnedAt = try container.decodeIfPresent(String.self, forKey: .pinnedAt)
    isPinned = try container.decodeIfPresent(Bool.self, forKey: .isPinned)

    if let nestedUser = try container.decodeIfPresent(MIRAUser.self, forKey: .user) {
      user = nestedUser
    } else {
      let username = try container.decodeIfPresent(String.self, forKey: .userUsername)
      let fullName = try container.decodeIfPresent(String.self, forKey: .userFullName)
      let profileImage = try container.decodeIfPresent(String.self, forKey: .userProfileImage)
      if userId != nil || username != nil || fullName != nil || profileImage != nil {
        user = MIRAUser(
          id: userId ?? id,
          username: username,
          usernameRequired: nil,
          onboardingRequired: nil,
          fullName: fullName,
          profileImage: profileImage,
          bio: nil,
          email: nil,
          phone: nil,
          phoneVerified: nil,
          followersCount: nil,
          followingCount: nil,
          postsCount: nil,
          isFollowing: nil,
          isPrivate: nil,
          isPremium: nil,
          language: nil
        )
      } else {
        user = nil
      }
    }
  }

  public func updating(liked: Bool? = nil, likesCount: Int? = nil, pinnedAt: String? = nil, clearPin: Bool = false) -> MIRAComment {
    MIRAComment(
      id: id,
      userId: userId,
      postId: postId,
      postUserId: postUserId,
      content: content,
      body: body,
      parentId: parentId,
      createdAt: createdAt,
      likesCount: likesCount ?? self.likesCount,
      likedByMe: liked ?? likedByMe,
      pinnedAt: clearPin ? nil : (pinnedAt ?? self.pinnedAt),
      isPinned: clearPin ? false : ((pinnedAt != nil) ? true : isPinned),
      user: user
    )
  }
}

public struct MIRAWallet: Codable, Hashable {
  public let balance: Int?
  public let premiumActive: Bool?
  public let premiumPlan: String?
}

public struct MIRAConversation: Codable, Identifiable, Hashable {
  public let id: String
  public let type: String?
  public let otherUserId: String?
  public let otherUsername: String?
  public let otherFullName: String?
  public let otherProfileImage: String?
  public let otherLastSeenAt: String?
  public let otherIsOnline: Bool?
  public let otherIsTyping: Bool?
  public let lastMessage: String?
  public let lastMessageTime: String?
  public let updatedAt: String?
  public let unreadCount: Int?
  public let groupId: String?
  public let groupName: String?
  public let memberCount: Int?

  public var displayName: String {
    groupName?.isEmpty == false ? groupName! : (otherUsername?.isEmpty == false ? otherUsername! : (otherFullName ?? "Chat"))
  }

  public var isGroup: Bool {
    type == "group" || groupId != nil
  }

  enum CodingKeys: String, CodingKey {
    case id, type
    case otherUser
    case otherUserId, otherUsername, otherFullName, otherProfileImage, otherLastSeenAt, otherIsOnline, otherIsTyping
    case lastMessage, lastMessageTime, updatedAt, unreadCount
    case groupId, groupName, memberCount
  }

  enum OtherUserKeys: String, CodingKey {
    case id, username, fullName, profileImage, lastSeenAt, isOnline, isTyping
  }

  public init(
    id: String,
    type: String?,
    otherUserId: String?,
    otherUsername: String?,
    otherFullName: String?,
    otherProfileImage: String?,
    otherLastSeenAt: String?,
    otherIsOnline: Bool?,
    otherIsTyping: Bool?,
    lastMessage: String?,
    lastMessageTime: String?,
    updatedAt: String?,
    unreadCount: Int?,
    groupId: String?,
    groupName: String?,
    memberCount: Int?
  ) {
    self.id = id
    self.type = type
    self.otherUserId = otherUserId
    self.otherUsername = otherUsername
    self.otherFullName = otherFullName
    self.otherProfileImage = otherProfileImage
    self.otherLastSeenAt = otherLastSeenAt
    self.otherIsOnline = otherIsOnline
    self.otherIsTyping = otherIsTyping
    self.lastMessage = lastMessage
    self.lastMessageTime = lastMessageTime
    self.updatedAt = updatedAt
    self.unreadCount = unreadCount
    self.groupId = groupId
    self.groupName = groupName
    self.memberCount = memberCount
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    id = try container.decode(String.self, forKey: .id)
    type = try? container.decodeIfPresent(String.self, forKey: .type)
    lastMessage = try? container.decodeIfPresent(String.self, forKey: .lastMessage)
    lastMessageTime = try? container.decodeIfPresent(String.self, forKey: .lastMessageTime)
    updatedAt = try? container.decodeIfPresent(String.self, forKey: .updatedAt)
    unreadCount = try? container.decodeIfPresent(Int.self, forKey: .unreadCount)
    groupId = try? container.decodeIfPresent(String.self, forKey: .groupId)
    groupName = try? container.decodeIfPresent(String.self, forKey: .groupName)
    memberCount = try? container.decodeIfPresent(Int.self, forKey: .memberCount)

    let nested = try? container.nestedContainer(keyedBy: OtherUserKeys.self, forKey: .otherUser)
    func nestedString(_ key: OtherUserKeys) -> String? {
      guard let nested else { return nil }
      return try? nested.decodeIfPresent(String.self, forKey: key)
    }
    func nestedBool(_ key: OtherUserKeys) -> Bool? {
      guard let nested else { return nil }
      return try? nested.decodeIfPresent(Bool.self, forKey: key)
    }
    otherUserId = (try? container.decodeIfPresent(String.self, forKey: .otherUserId)) ?? nestedString(.id)
    otherUsername = (try? container.decodeIfPresent(String.self, forKey: .otherUsername)) ?? nestedString(.username)
    otherFullName = (try? container.decodeIfPresent(String.self, forKey: .otherFullName)) ?? nestedString(.fullName)
    otherProfileImage = (try? container.decodeIfPresent(String.self, forKey: .otherProfileImage)) ?? nestedString(.profileImage)
    otherLastSeenAt = (try? container.decodeIfPresent(String.self, forKey: .otherLastSeenAt)) ?? nestedString(.lastSeenAt)
    otherIsOnline = (try? container.decodeIfPresent(Bool.self, forKey: .otherIsOnline)) ?? nestedBool(.isOnline)
    otherIsTyping = (try? container.decodeIfPresent(Bool.self, forKey: .otherIsTyping)) ?? nestedBool(.isTyping)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(id, forKey: .id)
    try container.encodeIfPresent(type, forKey: .type)
    try container.encodeIfPresent(otherUserId, forKey: .otherUserId)
    try container.encodeIfPresent(otherUsername, forKey: .otherUsername)
    try container.encodeIfPresent(otherFullName, forKey: .otherFullName)
    try container.encodeIfPresent(otherProfileImage, forKey: .otherProfileImage)
    try container.encodeIfPresent(otherLastSeenAt, forKey: .otherLastSeenAt)
    try container.encodeIfPresent(otherIsOnline, forKey: .otherIsOnline)
    try container.encodeIfPresent(otherIsTyping, forKey: .otherIsTyping)
    try container.encodeIfPresent(lastMessage, forKey: .lastMessage)
    try container.encodeIfPresent(lastMessageTime, forKey: .lastMessageTime)
    try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    try container.encodeIfPresent(unreadCount, forKey: .unreadCount)
    try container.encodeIfPresent(groupId, forKey: .groupId)
    try container.encodeIfPresent(groupName, forKey: .groupName)
    try container.encodeIfPresent(memberCount, forKey: .memberCount)
  }
}

public struct MIRAMessage: Decodable, Identifiable, Hashable {
  public let id: String
  public let groupId: String?
  public let senderId: String?
  public let receiverId: String?
  public let content: String?
  public let mediaUrl: String?
  public let mediaType: String?
  public let createdAt: String?
  public let username: String?
  public let fullName: String?
  public let profileImage: String?
}

public struct MIRAPresence: Decodable, Hashable {
  public let userId: String?
  public let lastSeenAt: String?
  public let isOnline: Bool?
  public let isTyping: Bool?
}

public struct MIRAAgoraTokenRequest: Encodable {
  public let channel: String
  public let role: String
  public let mode: String
}

public struct MIRAAgoraTokenResponse: Decodable, Hashable {
  public let appId: String?
  public let channel: String
  public let uid: UInt
  public let role: String
  public let mode: String
  public let token: String
  public let expiresIn: Int?
  public let expiresAt: String?
}

enum MIRACallStatus: String, Decodable, Hashable {
  case idle
  case creatingCall
  case ringing
  case incoming
  case accepted
  case connecting
  case active
  case declined
  case cancelled
  case missed
  case failed
  case ended
}

struct MIRACallSession: Decodable, Identifiable, Hashable {
  let id: String
  let callId: String?
  let callerUserId: String
  let calleeUserId: String
  let callerName: String?
  let callerAvatar: String?
  let calleeName: String?
  let calleeAvatar: String?
  let callType: String?
  let status: MIRACallStatus
  let roomId: String?
  let channelName: String
  let pushDeliveryStatus: String?
  let createdAt: String?
  let answeredAt: String?
  let endedAt: String?
  let timeoutAt: String?

  var resolvedId: String { callId ?? id }

  func agoraPresentation(currentUserId: String) -> MIRAAgoraCallPresentation {
    let isCaller = callerUserId == currentUserId
    let peerId = isCaller ? calleeUserId : callerUserId
    let peerName = isCaller ? (calleeName ?? "Video call") : (callerName ?? "Video call")
    let peerAvatar = isCaller ? calleeAvatar : callerAvatar
    return MIRAAgoraCallPresentation(
      callId: resolvedId,
      peerId: peerId,
      peerName: peerName,
      peerAvatar: peerAvatar,
      channel: channelName,
      mode: .video,
      role: .host
    )
  }
}

struct MIRACallStartBody: Encodable {
  let calleeUserId: String
  let callType: String

  init(calleeUserId: String, callType: String = "video") {
    self.calleeUserId = calleeUserId
    self.callType = callType
  }
}

struct MIRAVoIPTokenBody: Encodable {
  let token: String
  let deviceId: String
  let bundleId: String
  let environment: String
}

struct MIRAIncomingCallEnvelope: Decodable, Hashable {
  let call: MIRACallSession?
}

public struct MIRANotification: Decodable, Identifiable, Hashable {
  public let id: String
  public let type: String?
  public let title: String?
  public let body: String?
  public let data: FlexibleJSONText?
  public let isRead: FlexibleBool?
  public let createdAt: String?
}

public struct MIRAAuthResponse: Decodable, Hashable {
  public let accessToken: String
  public let tokenType: String?
  public let user: MIRAUser
}

public struct MIRAAuthLoginBody: Encodable {
  public let email: String
  public let password: String
}

public struct MIRAAuthRegisterBody: Encodable {
  public let email: String
  public let password: String
  public let username: String
  public let fullName: String
}

public struct MIRAAppleOAuthBody: Encodable {
  public let idToken: String
  public let email: String?
  public let fullName: String?
  public let appleUser: String?
}

public struct MIRAUploadImageBody: Encodable {
  public let image: String
  public let filename: String
}

public struct MIRAMediaUploadResponse: Decodable, Hashable {
  public let url: String?
  public let id: String?
  public let videoUid: String?
  public let uploadUrl: String?
  public let source: String?
}

public struct MIRAStreamPlaybackInfo: Decodable, Hashable {
  public let uid: String?
  public let hls: String?
  public let dash: String?
  public let thumbnail: String?
  public let ready: Bool?
}

public struct MIRALibraryCollection: Decodable, Identifiable, Hashable {
  public var id: String { collection ?? name ?? "collection" }
  public let collection: String?
  public let name: String?
  public let count: Int?
}

public struct MIRAWalletTransaction: Decodable, Identifiable, Hashable {
  public let id: String
  public let amount: Int?
  public let direction: String?
  public let reason: String?
  public let createdAt: String?
}

public struct CreatePostBody: Encodable {
  public let title: String
  public let content: String
  public let image: String?
  public let images: [String]
  public let mediaTypes: [String]
  public let mediaDimensions: [MIRAMediaDimension]
  public let editorOverlays: [MIRAEditorUploadMetadata]?
  public let location: String?
  public let postType: String?
  public let placeId: String?
  public let placeName: String?
  public let placeLat: Double?
  public let placeLng: Double?
  public let taggedUsers: [MIRATaggedUserPayload]?
  public let visibility: String
  public let clientRequestId: String

  public init(
    title: String,
    content: String,
    image: String?,
    images: [String],
    mediaTypes: [String],
    mediaDimensions: [MIRAMediaDimension],
    editorOverlays: [MIRAEditorUploadMetadata]? = nil,
    location: String? = nil,
    postType: String? = nil,
    placeId: String? = nil,
    placeName: String? = nil,
    placeLat: Double? = nil,
    placeLng: Double? = nil,
    taggedUsers: [MIRATaggedUserPayload]? = nil,
    visibility: String,
    clientRequestId: String
  ) {
    self.title = title
    self.content = content
    self.image = image
    self.images = images
    self.mediaTypes = mediaTypes
    self.mediaDimensions = mediaDimensions
    self.editorOverlays = editorOverlays
    self.location = location
    self.postType = postType
    self.placeId = placeId
    self.placeName = placeName
    self.placeLat = placeLat
    self.placeLng = placeLng
    self.taggedUsers = taggedUsers
    self.visibility = visibility
    self.clientRequestId = clientRequestId
  }
}

public struct MIRAEditorUploadMetadata: Encodable, Hashable {
  public let type: String
  public let mediaIndex: Int
  public let wasEdited: Bool
  public let editorVersion: String
  public let appliedFilter: String
  public let hasTextOverlay: Bool

  public init(mediaIndex: Int, metadata: MIRANativeEditedMediaMetadata) {
    self.type = "native_editor"
    self.mediaIndex = mediaIndex
    self.wasEdited = metadata.wasEdited
    self.editorVersion = metadata.editorVersion
    self.appliedFilter = metadata.appliedFilter
    self.hasTextOverlay = metadata.hasTextOverlay
  }
}

public struct CreateNoteBody: Encodable {
  public let body: String
  public let mediaUrl: String?
  public let color: String?
}

public struct CreateStatusBody: Encodable {
  public let content: String
  public let image: String?
  public let backgroundColor: String
  public let textColor: String
  public let visibility: String
  public let editorMetadata: MIRANativeEditedMediaMetadata?

  public init(
    content: String,
    image: String?,
    backgroundColor: String,
    textColor: String,
    visibility: String,
    editorMetadata: MIRANativeEditedMediaMetadata? = nil
  ) {
    self.content = content
    self.image = image
    self.backgroundColor = backgroundColor
    self.textColor = textColor
    self.visibility = visibility
    self.editorMetadata = editorMetadata
  }
}

public struct SendMessageBody: Encodable {
  public let receiverId: String
  public let content: String
  public let mediaUrl: String?
  public let mediaType: String?

  public init(receiverId: String, content: String, mediaUrl: String? = nil, mediaType: String? = nil) {
    self.receiverId = receiverId
    self.content = content
    self.mediaUrl = mediaUrl
    self.mediaType = mediaType
  }
}

public struct GroupMessageBody: Encodable {
  public let content: String
  public let mediaUrl: String?
  public let mediaType: String?

  public init(content: String, mediaUrl: String? = nil, mediaType: String? = nil) {
    self.content = content
    self.mediaUrl = mediaUrl
    self.mediaType = mediaType
  }
}

public struct CreateGroupChatBody: Encodable {
  public let name: String
  public let memberIds: [String]
}

public struct MIRAGroupChatCreatedResponse: Decodable, Hashable {
  public let id: String
  public let name: String?
  public let memberCount: Int?
  public let createdBy: String?
  public let createdAt: String?
}

public struct MIRAGroupInfo: Decodable, Hashable {
  public let id: String
  public let name: String?
  public let createdBy: String?
  public let memberCount: Int?
}

public struct MIRAGroupMessagesResponse: Decodable, Hashable {
  public let group: MIRAGroupInfo?
  public let messages: [MIRAMessage]
}

public struct TypingBody: Encodable {
  public let peerId: String
  public let isTyping: Bool
}

public struct NoteInteractionBody: Encodable {
  public let kind: String
  public let value: String?
}

public struct NoteInteractionResponse: Decodable {
  public let active: Bool?
  public let kind: String?
}

public struct NoteReportBody: Encodable {
  public let reason: String
  public let details: String?
}

public struct PostReportBody: Encodable {
  public let reportedType: String
  public let reportedId: String
  public let reason: String
  public let details: String?

  enum CodingKeys: String, CodingKey {
    case reportedType = "reported_type"
    case reportedId = "reported_id"
    case reason
    case details
  }
}

public struct FollowBody: Encodable {
  public let following: Bool
}

public struct LikeBody: Encodable {
  public let liked: Bool
}

public struct PostPinBody: Encodable {
  public let pinned: Bool
}

public struct CommentPinBody: Encodable {
  public let pinned: Bool
}

public struct SaveCollectionBody: Encodable {
  public let collection: String
}

public struct FollowResponse: Decodable {
  public let following: Bool?
  public let followingCount: Int?
  public let followersCount: Int?
}

public struct PostLikeResponse: Decodable {
  public let liked: Bool?
  public let likesCount: Int?
  public let saved: Bool?
  public let savesCount: Int?
  public let commentsCount: Int?
}

public struct PostSaveResponse: Decodable {
  public let saved: Bool?
  public let savesCount: Int?
  public let liked: Bool?
  public let likesCount: Int?
  public let commentsCount: Int?
}

public struct CommentLikeResponse: Decodable {
  public let liked: Bool?
  public let likesCount: Int?
}

public struct CommentPinResponse: Decodable {
  public let pinned: Bool?
  public let pinnedAt: String?
}

public struct CommentMutationResponse: Decodable {
  public let deleted: Bool?
  public let hidden: Bool?
  public let commentsCount: Int?
}

public struct NoteCommentBody: Encodable {
  public let body: String
  public let parentId: String?
}

public struct PostCommentBody: Encodable {
  public let content: String
  public let parentId: String?

  public init(content: String, parentId: String? = nil) {
    self.content = content
    self.parentId = parentId
  }
}

public struct FlexibleStringArray: Codable, Hashable {
  public let values: [String]

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let array = try? container.decode([String].self) {
      values = array
      return
    }
    if let string = try? container.decode(String.self) {
      if string.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("["),
         let data = string.data(using: .utf8),
         let decoded = try? JSONDecoder().decode([String].self, from: data) {
        values = decoded
      } else if string.isEmpty {
        values = []
      } else {
        values = [string]
      }
      return
    }
    values = []
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(values)
  }
}

public struct FlexibleMediaDimensions: Codable, Hashable {
  public let values: [MIRAMediaDimension]

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let array = try? container.decode([MIRAMediaDimension].self) {
      values = array
      return
    }
    if let dimension = try? container.decode(MIRAMediaDimension.self) {
      values = [dimension]
      return
    }
    if let dictionary = try? container.decode([String: MIRAMediaDimension].self) {
      values = dictionary.keys.sorted().compactMap { dictionary[$0] }
      return
    }
    if let string = try? container.decode(String.self) {
      let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
      if trimmed.isEmpty {
        values = []
        return
      }
      if let data = trimmed.data(using: .utf8) {
        if let decoded = try? JSONDecoder().decode([MIRAMediaDimension].self, from: data) {
          values = decoded
          return
        }
        if let decoded = try? JSONDecoder().decode(MIRAMediaDimension.self, from: data) {
          values = [decoded]
          return
        }
        if let decoded = try? JSONDecoder().decode([String: MIRAMediaDimension].self, from: data) {
          values = decoded.keys.sorted().compactMap { decoded[$0] }
          return
        }
      }
      values = [MIRAMediaDimension(width: nil, height: nil, ratio: nil, format: trimmed, type: nil)]
      return
    }
    values = []
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(values)
  }
}

public struct FlexibleBool: Codable, Hashable {
  public let value: Bool

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let bool = try? container.decode(Bool.self) {
      value = bool
    } else if let int = try? container.decode(Int.self) {
      value = int != 0
    } else if let string = try? container.decode(String.self) {
      value = ["true", "1", "yes"].contains(string.lowercased())
    } else {
      value = false
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(value)
  }
}

public struct FlexibleJSONText: Codable, Hashable {
  public let raw: String

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let string = try? container.decode(String.self) {
      raw = string
      return
    }
    if let object = try? container.decode([String: String].self),
       let data = try? JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]),
       let string = String(data: data, encoding: .utf8) {
      raw = string
      return
    }
    raw = "{}"
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(raw)
  }
}
