// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_reason`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

NativeCoreStatus initNativeCore() =>
    RustLib.instance.api.crateApiCoreInitNativeCore();

List<RankedFeedItem> rankForYouItems({required List<FeedSignal> items}) =>
    RustLib.instance.api.crateApiCoreRankForYouItems(items: items);

class FeedSignal {
  final String id;
  final String title;
  final String category;
  final String location;
  final double likes;
  final double comments;
  final double shares;
  final double saves;
  final double impressions;
  final double ageHours;
  final double interestMatch;
  final double distanceKm;

  const FeedSignal({
    required this.id,
    required this.title,
    required this.category,
    required this.location,
    required this.likes,
    required this.comments,
    required this.shares,
    required this.saves,
    required this.impressions,
    required this.ageHours,
    required this.interestMatch,
    required this.distanceKm,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      category.hashCode ^
      location.hashCode ^
      likes.hashCode ^
      comments.hashCode ^
      shares.hashCode ^
      saves.hashCode ^
      impressions.hashCode ^
      ageHours.hashCode ^
      interestMatch.hashCode ^
      distanceKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedSignal &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          category == other.category &&
          location == other.location &&
          likes == other.likes &&
          comments == other.comments &&
          shares == other.shares &&
          saves == other.saves &&
          impressions == other.impressions &&
          ageHours == other.ageHours &&
          interestMatch == other.interestMatch &&
          distanceKm == other.distanceKm;
}

class NativeCoreStatus {
  final String engineName;
  final bool rustReady;
  final bool cppReady;
  final double sampleScore;
  final String message;

  const NativeCoreStatus({
    required this.engineName,
    required this.rustReady,
    required this.cppReady,
    required this.sampleScore,
    required this.message,
  });

  @override
  int get hashCode =>
      engineName.hashCode ^
      rustReady.hashCode ^
      cppReady.hashCode ^
      sampleScore.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCoreStatus &&
          runtimeType == other.runtimeType &&
          engineName == other.engineName &&
          rustReady == other.rustReady &&
          cppReady == other.cppReady &&
          sampleScore == other.sampleScore &&
          message == other.message;
}

class RankedFeedItem {
  final String id;
  final String title;
  final double score;
  final String reason;

  const RankedFeedItem({
    required this.id,
    required this.title,
    required this.score,
    required this.reason,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ score.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RankedFeedItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          score == other.score &&
          reason == other.reason;
}
