name = "flames-up-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "flames-up-super-secret-jwt-key-2024"
CLOUDFLARE_ACCOUNT_ID = "2ca88b3551321681a5f9434814f38ec8"
CLOUDFLARE_IMAGES_TOKEN = "cfut_MXsqGuOrmVgQhTWTHRCDIAI2qXehcf90dQ3xf8Sif7c52058"
CLOUDFLARE_STREAM_TOKEN = "cfut_MXsqGuOrmVgQhTWTHRCDIAI2qXehcf90dQ3xf8Sif7c52058"
GOOGLE_MAPS_API_KEY = ""
FRONTEND_URL = "https://flames-up.com"

[[d1_databases]]
binding = "DB"
database_name = "flames-up-db"
database_id = "<YOUR_D1_DATABASE_ID>"

[[kv_namespaces]]
binding = "KV"
id = "<YOUR_KV_NAMESPACE_ID>"

[env.production]
name = "flames-up-api"

[env.production.vars]
JWT_SECRET = ""
FRONTEND_URL = "https://flames-up.com"
