// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCoreInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 523177244;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flames_native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCoreInitApp();

  NativeCoreStatus crateApiCoreInitNativeCore();

  List<RankedFeedItem> crateApiCoreRankForYouItems({
    required List<FeedSignal> items,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCoreInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  NativeCoreStatus crateApiCoreInitNativeCore() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_core_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreInitNativeCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitNativeCoreConstMeta =>
      const TaskConstMeta(debugName: "init_native_core", argNames: []);

  @override
  List<RankedFeedItem> crateApiCoreRankForYouItems({
    required List<FeedSignal> items,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_feed_signal(items, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranked_feed_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreRankForYouItemsConstMeta,
        argValues: [items],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreRankForYouItemsConstMeta =>
      const TaskConstMeta(debugName: "rank_for_you_items", argNames: ["items"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FeedSignal dco_decode_feed_signal(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return FeedSignal(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      location: dco_decode_String(arr[3]),
      likes: dco_decode_f_64(arr[4]),
      comments: dco_decode_f_64(arr[5]),
      shares: dco_decode_f_64(arr[6]),
      saves: dco_decode_f_64(arr[7]),
      impressions: dco_decode_f_64(arr[8]),
      ageHours: dco_decode_f_64(arr[9]),
      interestMatch: dco_decode_f_64(arr[10]),
      distanceKm: dco_decode_f_64(arr[11]),
    );
  }

  @protected
  List<FeedSignal> dco_decode_list_feed_signal(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_feed_signal).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RankedFeedItem> dco_decode_list_ranked_feed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ranked_feed_item).toList();
  }

  @protected
  NativeCoreStatus dco_decode_native_core_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NativeCoreStatus(
      engineName: dco_decode_String(arr[0]),
      rustReady: dco_decode_bool(arr[1]),
      cppReady: dco_decode_bool(arr[2]),
      sampleScore: dco_decode_f_64(arr[3]),
      message: dco_decode_String(arr[4]),
    );
  }

  @protected
  RankedFeedItem dco_decode_ranked_feed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RankedFeedItem(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      score: dco_decode_f_64(arr[2]),
      reason: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FeedSignal sse_decode_feed_signal(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_likes = sse_decode_f_64(deserializer);
    var var_comments = sse_decode_f_64(deserializer);
    var var_shares = sse_decode_f_64(deserializer);
    var var_saves = sse_decode_f_64(deserializer);
    var var_impressions = sse_decode_f_64(deserializer);
    var var_ageHours = sse_decode_f_64(deserializer);
    var var_interestMatch = sse_decode_f_64(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    return FeedSignal(
      id: var_id,
      title: var_title,
      category: var_category,
      location: var_location,
      likes: var_likes,
      comments: var_comments,
      shares: var_shares,
      saves: var_saves,
      impressions: var_impressions,
      ageHours: var_ageHours,
      interestMatch: var_interestMatch,
      distanceKm: var_distanceKm,
    );
  }

  @protected
  List<FeedSignal> sse_decode_list_feed_signal(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FeedSignal>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed_signal(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RankedFeedItem> sse_decode_list_ranked_feed_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RankedFeedItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ranked_feed_item(deserializer));
    }
    return ans_;
  }

  @protected
  NativeCoreStatus sse_decode_native_core_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_engineName = sse_decode_String(deserializer);
    var var_rustReady = sse_decode_bool(deserializer);
    var var_cppReady = sse_decode_bool(deserializer);
    var var_sampleScore = sse_decode_f_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    return NativeCoreStatus(
      engineName: var_engineName,
      rustReady: var_rustReady,
      cppReady: var_cppReady,
      sampleScore: var_sampleScore,
      message: var_message,
    );
  }

  @protected
  RankedFeedItem sse_decode_ranked_feed_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_score = sse_decode_f_64(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return RankedFeedItem(
      id: var_id,
      title: var_title,
      score: var_score,
      reason: var_reason,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_feed_signal(FeedSignal self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_f_64(self.likes, serializer);
    sse_encode_f_64(self.comments, serializer);
    sse_encode_f_64(self.shares, serializer);
    sse_encode_f_64(self.saves, serializer);
    sse_encode_f_64(self.impressions, serializer);
    sse_encode_f_64(self.ageHours, serializer);
    sse_encode_f_64(self.interestMatch, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
  }

  @protected
  void sse_encode_list_feed_signal(
    List<FeedSignal> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed_signal(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ranked_feed_item(
    List<RankedFeedItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ranked_feed_item(item, serializer);
    }
  }

  @protected
  void sse_encode_native_core_status(
    NativeCoreStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.engineName, serializer);
    sse_encode_bool(self.rustReady, serializer);
    sse_encode_bool(self.cppReady, serializer);
    sse_encode_f_64(self.sampleScore, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_ranked_feed_item(
    RankedFeedItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.score, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
